media:
  input: assets/images
  output: /assets/images

content:

  # Gitarrenprojekte
  - name: guitars
    label: "Gitarren"
    type: collection
    path: "_posts/guitars"
    format: md

    slug: "{{fields.title | slugify}}"

    fields:
      - name: title
        label: "Gitarrenname"
        type: string
        required: true

      - name: build_year
        label: "Baujahr"
        type: string

      - name: guitar_type
        label: "Typ"
        type: string

      - name: cover_image
        label: "Titelbild"
        type: image

      - name: body
        label: "Beschreibung"
        type: rich-text

  # Laufende Bauberichte
  - name: build_reports
    label: "Bauberichte"
    type: collection
    path: "_posts/build-reports"
    format: md

    slug: "{{year}}-{{month}}-{{day}}-{{fields.title | slugify}}"

    fields:
      - name: title
        label: "Titel"
        type: string
        required: true

      - name: date
        label: "Datum"
        type: date
        required: true

      - name: body
        label: "Baubericht"
        type: rich-text

  # Werkstatt
  - name: workshop
    label: "Werkstatt"
    type: collection
    path: "_posts/workshop"
    format: md

    slug: "{{fields.title | slugify}}"

    fields:
      - name: title
        label: "Titel"
        type: string
        required: true

      - name: body
        label: "Inhalt"
        type: rich-text
