media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: "Bauberichte"
    type: collection
    path: "_posts"
    fields:
      - name: title
        label: "Titel"
        type: string
      - name: body
        label: "Inhalt"
        type: rich-text
