
backend:
  name: github
  repo: ugrosche/grosche-guitars

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "bauberichte"
    label: "Bauberichte"
    folder: "_pages"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Titel des Projekts"
        name: "title"
        widget: "string"

      - label: "Datum"
        name: "date"
        widget: "datetime"

      - label: "Baubericht"
        name: "body"
        widget: "markdown"
